version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  products-service:
    build: ./products-service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/products_db
    ports:
      - "8000:8000"
    depends_on:
      - db

  products-frontend:
    build: ./products-frontend
    environment:
      - STREAMLIT_SERVER_PORT=8501
    ports:
      - "8501:8501"
    depends_on:
      - products-service

volumes:
  pgdata:
